
import localFont from 'next/font/local'
import "./globals.css";
import { Providers } from '../redux/providers'
import { Provider } from 'react-redux'
import store from '../redux/store'
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
      <Providers>
        {children}
      </Providers>
      </body>
    </html>
  );
}



// import localFont from 'next/font/local'
// import "./globals.css";
// import { Providers } from '../redux/providers'
// import { Provider } from 'react-redux'
// import store from '../redux/store'
// import Sidebar from '../components/Sidebar';
// import Navbar from '../components/Navbar';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Providers>
//           <div className="flex h-screen">
//             <Sidebar />
//             <div className="flex-1">
//               <Navbar />
//               <main className="p-4">{children}</main>
//             </div>
//           </div>
//         </Providers>
//       </body>
//     </html>
//   );
// }